/*
 * hb_helvetica.c — render text using a bitmap version of Helvetica
 * pre-generated by sdk/tools/render_font.py from the system TTF.
 *
 * Advantage over hb_text.c (built-in 8x8 bitmap font): real Helvetica
 * glyph shapes, proportional advance widths, much nicer visual quality.
 *
 * Per character: one MIPI set_window + bulk pixel push via
 * hb_mipi_blit_glyph (~1 MIPI long-packet per glyph).
 */

#include "hb_sdk.h"

extern const int     hb_font_helvetica_cell_w;
extern const int     hb_font_helvetica_cell_h;
extern const int     hb_font_helvetica_first;
extern const int     hb_font_helvetica_last;
extern const uint8_t hb_font_helvetica_advance[];
extern const uint8_t hb_font_helvetica_bitmap[];

extern void hb_mipi_blit_glyph(int16_t x, int16_t y,
                               int16_t w, int16_t h,
                               const uint8_t *gray, uint8_t threshold,
                               hb_color_t fg, hb_color_t bg, int draw_bg);

static int glyph_index(uint8_t code)
{
    int first = hb_font_helvetica_first;
    int last  = hb_font_helvetica_last;
    if (code < first || code > last) return '?' - first;
    return code - first;
}

/* Draw `s` at (x,y) in `fg` over `bg`. Returns x past last drawn glyph. */
int16_t hb_helvetica_draw(int16_t x, int16_t y, const char *s,
                          hb_color_t fg, hb_color_t bg)
{
    int cw = hb_font_helvetica_cell_w;
    int ch = hb_font_helvetica_cell_h;
    int16_t pen = x;
    while (*s) {
        uint8_t c = (uint8_t)*s++;
        int idx = glyph_index(c);
        const uint8_t *cell = hb_font_helvetica_bitmap + idx * cw * ch;
        hb_mipi_blit_glyph(pen, y, (int16_t)cw, (int16_t)ch,
                           cell, 128, fg, bg, 1);
        pen += hb_font_helvetica_advance[idx];
    }
    return pen;
}

/* Measure string width in pixels without drawing. */
int16_t hb_helvetica_width(const char *s)
{
    int16_t w = 0;
    while (*s) {
        uint8_t c = (uint8_t)*s++;
        w += hb_font_helvetica_advance[glyph_index(c)];
    }
    return w;
}

int hb_helvetica_line_height(void)
{
    return hb_font_helvetica_cell_h;
}
