#!/usr/bin/env python3
"""
render_font.py — generate a C array bitmap font from a TTF.

Output: hb_font_helvetica.c with a static const uint8_t array of
grayscale glyph bitmaps. ASCII printable range (0x20-0x7E = 95 chars).

Usage:
    python3 render_font.py <ttf_path> <pixel_size> <output_dir>
"""
import sys
import os
from PIL import Image, ImageFont, ImageDraw

if len(sys.argv) < 4:
    print(__doc__)
    sys.exit(1)

ttf, size_str, outdir = sys.argv[1], sys.argv[2], sys.argv[3]
size = int(size_str)
os.makedirs(outdir, exist_ok=True)

font = ImageFont.truetype(ttf, size)

# Determine grid dimensions. We'll use a fixed cell size large enough
# for all printable ASCII glyphs. Measure max width/height.
max_w, max_h = 0, 0
ascent, descent = font.getmetrics()
cell_h = ascent + descent
for ch in range(0x20, 0x7F):
    bbox = font.getbbox(chr(ch))
    w = bbox[2] - bbox[0]
    if w > max_w:
        max_w = w
cell_w = max_w + 2  # small horizontal padding

# Render each glyph centered into its cell.
GLYPHS = list(range(0x20, 0x7F))
N = len(GLYPHS)

# We pack as: cell_w x cell_h per glyph, 1 byte per pixel grayscale (0-255).
# For lookup at runtime: glyph[code - 0x20] starts at (code - 0x20) * cell_w * cell_h.
# Width per glyph is stored in a side array (proportional layout).

per_glyph_advance = []
glyph_bytes = bytearray()

for code in GLYPHS:
    img = Image.new("L", (cell_w, cell_h), 0)
    d = ImageDraw.Draw(img)
    # Draw at baseline; PIL handles this by passing top-left such that
    # the baseline ends up at `ascent`.
    d.text((1, 0), chr(code), 255, font=font)
    # Compute advance width
    advance = int(font.getlength(chr(code)))
    if advance < 1: advance = 1
    if advance > cell_w: advance = cell_w
    per_glyph_advance.append(advance)
    glyph_bytes.extend(img.tobytes())

basename = os.path.splitext(os.path.basename(ttf))[0].lower()
header = """\
/*
 * AUTO-GENERATED by sdk/tools/render_font.py from {ttf}.
 * Do not edit by hand.
 *
 * Bitmap font cell layout: {cw}x{ch} per glyph, 8bpp grayscale.
 * ASCII codes 0x20..0x7E (printable). Cell index = code - 0x20.
 */
#include "hb_sdk.h"

""".format(ttf=os.path.basename(ttf), cw=cell_w, ch=cell_h)

c_out = []
c_out.append(header)
c_out.append("const int hb_font_{}_cell_w = {};".format(basename, cell_w))
c_out.append("const int hb_font_{}_cell_h = {};".format(basename, cell_h))
c_out.append("const int hb_font_{}_first = 0x{:02X};".format(basename, 0x20))
c_out.append("const int hb_font_{}_last  = 0x{:02X};".format(basename, 0x7E))
c_out.append("")
c_out.append("const uint8_t hb_font_{}_advance[{}] = {{".format(basename, N))
for i in range(0, N, 16):
    chunk = per_glyph_advance[i:i+16]
    c_out.append("    " + ", ".join(str(a) for a in chunk) + ",")
c_out.append("};")
c_out.append("")
c_out.append("const uint8_t hb_font_{}_bitmap[{}] = {{".format(basename, len(glyph_bytes)))
hexstrs = ["0x{:02X}".format(b) for b in glyph_bytes]
for i in range(0, len(hexstrs), 16):
    c_out.append("    " + ", ".join(hexstrs[i:i+16]) + ",")
c_out.append("};")
c_out.append("")

out_path = os.path.join(outdir, "hb_font_{}.c".format(basename))
with open(out_path, "w") as f:
    f.write("\n".join(c_out))

print("wrote {} ({} bytes for {} glyphs, cell {}x{})".format(
    out_path, len(glyph_bytes), N, cell_w, cell_h))
